In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    "Emp_ID":[101,102,103,104,105,106,107,108],
    "Name":["Rahul","Priya","Amit","Sneha","Arjun","Kiran","Pooja","Vijay"],
    "Department":["IT","HR","IT","Sales","HR","Sales","IT","HR"],
    "Age":[25,28,30,24,29,31,27,26],
    "Salary":[50000,45000,60000,40000,52000,48000,65000,47000],
    "City":["Delhi","Mumbai","Delhi","Chennai","Hyderabad","Mumbai","Delhi","Chennai"],
    "Experience":[2,4,6,1,5,7,3,2]
})

In [3]:
df

   Emp_ID   Name Department  Age  Salary       City  Experience
0     101  Rahul         IT   25   50000      Delhi           2
1     102  Priya         HR   28   45000     Mumbai           4
2     103   Amit         IT   30   60000      Delhi           6
3     104  Sneha      Sales   24   40000    Chennai           1
4     105  Arjun         HR   29   52000  Hyderabad           5
5     106  Kiran      Sales   31   48000     Mumbai           7
6     107  Pooja         IT   27   65000      Delhi           3
7     108  Vijay         HR   26   47000    Chennai           2

In [4]:
# Exploring dataset

print("First 5 rows:\n")
print(df.head())
print("-------------------------------------------------------------------")
print("Last 3 rows:\n")
print(df.tail(3))
print("-------------------------------------------------------------------")
print("Shape of the DataFrame:\n")
print(df.shape)
print("-------------------------------------------------------------------")
print("Summary statistics:\n")
print(df.describe())
print("-------------------------------------------------------------------")
print("DataFrame Information:\n")
print(df.info())

First 5 rows:

   Emp_ID   Name Department  Age  Salary       City  Experience
0     101  Rahul         IT   25   50000      Delhi           2
1     102  Priya         HR   28   45000     Mumbai           4
2     103   Amit         IT   30   60000      Delhi           6
3     104  Sneha      Sales   24   40000    Chennai           1
4     105  Arjun         HR   29   52000  Hyderabad           5
-------------------------------------------------------------------
Last 3 rows:

   Emp_ID   Name Department  Age  Salary     City  Experience
5     106  Kiran      Sales   31   48000   Mumbai           7
6     107  Pooja         IT   27   65000    Delhi           3
7     108  Vijay         HR   26   47000  Chennai           2
-------------------------------------------------------------------
Shape of the DataFrame:

(8, 7)
-------------------------------------------------------------------
Summary statistics:

          Emp_ID       Age        Salary  Experience
count    8.00000   8.00000      8.000000     8.00000
mean   104.50000  27.50000  50875.000000     3.75000
std      2.44949   2.44949   8114.141095     2.12132
min    101.00000  24.00000  40000.000000     1.00000
25%    102.75000  25.75000  46500.000000     2.00000
50%    104.50000  27.50000  49000.000000     3.50000
75%    106.25000  29.25000  54000.000000     5.25000
max    108.00000  31.00000  65000.000000     7.00000
-------------------------------------------------------------------
DataFrame Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      8 non-null      int64
 1   Name        8 non-null      object
 2   Department  8 non-null      object
 3   Age         8 non-null      int64
 4   Salary      8 non-null      int64
 5   City        8 non-null      object
 6   Experience  8 non-null      int64
dtypes: int64(4), object(3)
memory usage: 580.0+ bytes
None

In [5]:
# Data Selection

print("Name and Salary:\n")
print(df[["Name","Salary"]])
print("-------------------------------------------------------------------")
print("First Employee:\n")
print(df.head(1))
print("-------------------------------------------------------------------")
print("employees from 2 to 5:\n")
print(df[2:6])
print("-------------------------------------------------------------------")
print("Salary of Rahul:\n")
print(df[df["Name"]=="Rahul"]["Salary"])
print("-------------------------------------------------------------------")
print("City of employee 105:\n")
print(df[df["Emp_ID"]==105]["City"])

Name and Salary:

    Name  Salary
0  Rahul   50000
1  Priya   45000
2   Amit   60000
3  Sneha   40000
4  Arjun   52000
5  Kiran   48000
6  Pooja   65000
7  Vijay   47000
-------------------------------------------------------------------
First Employee:

   Emp_ID   Name Department  Age  Salary   City  Experience
0     101  Rahul         IT   25   50000  Delhi           2
-------------------------------------------------------------------
employees from 2 to 5:

   Emp_ID   Name Department  Age  Salary       City  Experience
2     103   Amit         IT   30   60000      Delhi           6
3     104  Sneha      Sales   24   40000    Chennai           1
4     105  Arjun         HR   29   52000  Hyderabad           5
5     106  Kiran      Sales   31   48000     Mumbai           7
-------------------------------------------------------------------
Salary of Rahul:

0    50000
Name: Salary, dtype: int64
-------------------------------------------------------------------
City of employee 105:

4    Hyderabad
Name: City, dtype: object

In [6]:
#Filtering Data

print("employees salary greater than 50k:\n")
print(df[df["Salary"]>50000])
print("-------------------------------------------------------------------")
print("employees from Delhi:\n")
print(df[df["City"] == "Delhi"])
print("-------------------------------------------------------------------")
print("employees from HR dept.:\n")
print(df[df["Department"] == "HR"])
print("-------------------------------------------------------------------")
print("employees age who are greater than 25:\n")
print(df[df["Age"]>27])
print("-------------------------------------------------------------------")
print("employees who's salary between 45k to 55k:\n")
print(df[df["Salary"].between(45000,55000)])
print("-------------------------------------------------------------------")
print("employees from delhi or mumbai:\n")
print(df[df["City"].isin(["Delhi","Mumbai"])])
print("-------------------------------------------------------------------")
print("employee from it dept experience is greatter than 2:\n")
print(df[(df["Department"]=="HR") & (df["Experience"]>2)])
print("-------------------------------------------------------------------")
print("employees whose name is priya or rahul:\n")
print(df[df["Name"].isin(["Priya","Rahul"])])

employees salary greater than 50k:

   Emp_ID   Name Department  Age  Salary       City  Experience
2     103   Amit         IT   30   60000      Delhi           6
4     105  Arjun         HR   29   52000  Hyderabad           5
6     107  Pooja         IT   27   65000      Delhi           3
-------------------------------------------------------------------
employees from Delhi:

   Emp_ID   Name Department  Age  Salary   City  Experience
0     101  Rahul         IT   25   50000  Delhi           2
2     103   Amit         IT   30   60000  Delhi           6
6     107  Pooja         IT   27   65000  Delhi           3
-------------------------------------------------------------------
employees from HR dept.:

   Emp_ID   Name Department  Age  Salary       City  Experience
1     102  Priya         HR   28   45000     Mumbai           4
4     105  Arjun         HR   29   52000  Hyderabad           5
7     108  Vijay         HR   26   47000    Chennai           2
-------------------------------------------------------------------
employees age who are greater than 25:

   Emp_ID   Name Department  Age  Salary       City  Experience
1     102  Priya         HR   28   45000     Mumbai           4
2     103   Amit         IT   30   60000      Delhi           6
4     105  Arjun         HR   29   52000  Hyderabad           5
5     106  Kiran      Sales   31   48000     Mumbai           7
-------------------------------------------------------------------
employees who's salary between 45k to 55k:

   Emp_ID   Name Department  Age  Salary       City  Experience
0     101  Rahul         IT   25   50000      Delhi           2
1     102  Priya         HR   28   45000     Mumbai           4
4     105  Arjun         HR   29   52000  Hyderabad           5
5     106  Kiran      Sales   31   48000     Mumbai           7
7     108  Vijay         HR   26   47000    Chennai           2
-------------------------------------------------------------------
employees from delhi or mumbai:

   Emp_ID   Name Department  Age  Salary    City  Experience
0     101  Rahul         IT   25   50000   Delhi           2
1     102  Priya         HR   28   45000  Mumbai           4
2     103   Amit         IT   30   60000   Delhi           6
5     106  Kiran      Sales   31   48000  Mumbai           7
6     107  Pooja         IT   27   65000   Delhi           3
-------------------------------------------------------------------
employee from it dept experience is greatter than 2:

   Emp_ID   Name Department  Age  Salary       City  Experience
1     102  Priya         HR   28   45000     Mumbai           4
4     105  Arjun         HR   29   52000  Hyderabad           5
-------------------------------------------------------------------
employees whose name is priya or rahul:

   Emp_ID   Name Department  Age  Salary    City  Experience
0     101  Rahul         IT   25   50000   Delhi           2
1     102  Priya         HR   28   45000  Mumbai           4

In [7]:
# Data Cleaning

print("Checking for Null values:\n")
print(df.isna())
print("-------------------------------------------------------------------")
print("Number of Missing Values:\n")
print(df.isna().sum())
print("-------------------------------------------------------------------")
print("Checking for duplicate values:\n")
print(df.duplicated())
print("-------------------------------------------------------------------")
print("if any duplicates are these removing them:\n")
print(df.drop_duplicates())

Checking for Null values:

   Emp_ID   Name  Department    Age  Salary   City  Experience
0   False  False       False  False   False  False       False
1   False  False       False  False   False  False       False
2   False  False       False  False   False  False       False
3   False  False       False  False   False  False       False
4   False  False       False  False   False  False       False
5   False  False       False  False   False  False       False
6   False  False       False  False   False  False       False
7   False  False       False  False   False  False       False
-------------------------------------------------------------------
Number of Missing Values:

Emp_ID        0
Name          0
Department    0
Age           0
Salary        0
City          0
Experience    0
dtype: int64
-------------------------------------------------------------------
Checking for duplicate values:

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool
-------------------------------------------------------------------
if any duplicates are these removing them:

   Emp_ID   Name Department  Age  Salary       City  Experience
0     101  Rahul         IT   25   50000      Delhi           2
1     102  Priya         HR   28   45000     Mumbai           4
2     103   Amit         IT   30   60000      Delhi           6
3     104  Sneha      Sales   24   40000    Chennai           1
4     105  Arjun         HR   29   52000  Hyderabad           5
5     106  Kiran      Sales   31   48000     Mumbai           7
6     107  Pooja         IT   27   65000      Delhi           3
7     108  Vijay         HR   26   47000    Chennai           2

In [8]:
# Data Transformation
# "Salary after bonus of 10%
df["Bonus"] = df["Salary"].apply(lambda x: x*0.10)
# Total Salary
df["Total Salary"] = df["Salary"]+df["Bonus"]
# converting cities to Upper case
df["City"] = df["City"].str.upper()
# Replacing delhi with new delhi
df.replace("DELHI","NEW DELHI",inplace=True)
# Renaming column salary to montly salary
df.rename(columns={"Salary":"Montly Salary"},inplace=True)
df

,Emp_ID,Name,Department,Age,Montly Salary,City,Experience,Bonus,Total Salary
0,101,Rahul,IT,25,50000,NEW DELHI,2,5000.0,55000.0
1,102,Priya,HR,28,45000,MUMBAI,4,4500.0,49500.0
2,103,Amit,IT,30,60000,NEW DELHI,6,6000.0,66000.0
3,104,Sneha,Sales,24,40000,CHENNAI,1,4000.0,44000.0
4,105,Arjun,HR,29,52000,HYDERABAD,5,5200.0,57200.0
5,106,Kiran,Sales,31,48000,MUMBAI,7,4800.0,52800.0
6,107,Pooja,IT,27,65000,NEW DELHI,3,6500.0,71500.0
7,108,Vijay,HR,26,47000,CHENNAI,2,4700.0,51700.0

In [9]:
# Sorting
df.sort_values(["Department","Montly Salary"],ascending=[True,True])

,Emp_ID,Name,Department,Age,Montly Salary,City,Experience,Bonus,Total Salary
1,102,Priya,HR,28,45000,MUMBAI,4,4500.0,49500.0
7,108,Vijay,HR,26,47000,CHENNAI,2,4700.0,51700.0
4,105,Arjun,HR,29,52000,HYDERABAD,5,5200.0,57200.0
0,101,Rahul,IT,25,50000,NEW DELHI,2,5000.0,55000.0
2,103,Amit,IT,30,60000,NEW DELHI,6,6000.0,66000.0
6,107,Pooja,IT,27,65000,NEW DELHI,3,6500.0,71500.0
3,104,Sneha,Sales,24,40000,CHENNAI,1,4000.0,44000.0
5,106,Kiran,Sales,31,48000,MUMBAI,7,4800.0,52800.0

In [10]:
# Groupby

print("\n#avg salary in each dept.\n")
print(df.groupby("Department")["Montly Salary"].mean())
print("\n#max salary in each dept.\n")
print(df.groupby("Department")["Montly Salary"].max())
print("\n#min salary in each dept.\n")
print(df.groupby("Department")["Montly Salary"].min())
print("\n#total salary in each dept.\n")
print(df.groupby("Department")["Montly Salary"].sum())
print("\n#no of employees in each dept.\n")
print(df.groupby("Department")["Emp_ID"].count())
print("\n#Avg exp in eacj dept.\n")
print(df.groupby("Department")["Experience"].mean())

#avg salary in each dept.

Department
HR       48000.000000
IT       58333.333333
Sales    44000.000000
Name: Montly Salary, dtype: float64

#max salary in each dept.

Department
HR       52000
IT       65000
Sales    48000
Name: Montly Salary, dtype: int64

#min salary in each dept.

Department
HR       45000
IT       50000
Sales    40000
Name: Montly Salary, dtype: int64

#total salary in each dept.

Department
HR       144000
IT       175000
Sales     88000
Name: Montly Salary, dtype: int64

#no of employees in each dept.

Department
HR       3
IT       3
Sales    2
Name: Emp_ID, dtype: int64

#Avg exp in eacj dept.

Department
HR       3.666667
IT       3.666667
Sales    4.000000
Name: Experience, dtype: float64

In [14]:
melted_data = df.melt(
    id_vars=["Emp_ID", "Name", "Department"],
    value_vars=["Age", "Montly Salary", "Experience"],
    var_name="Attribute",
    value_name="Value"
)

melted_data

    Emp_ID   Name Department      Attribute  Value
0      101  Rahul         IT            Age     25
1      102  Priya         HR            Age     28
2      103   Amit         IT            Age     30
3      104  Sneha      Sales            Age     24
4      105  Arjun         HR            Age     29
5      106  Kiran      Sales            Age     31
6      107  Pooja         IT            Age     27
7      108  Vijay         HR            Age     26
8      101  Rahul         IT  Montly Salary  50000
9      102  Priya         HR  Montly Salary  45000
10     103   Amit         IT  Montly Salary  60000
11     104  Sneha      Sales  Montly Salary  40000
12     105  Arjun         HR  Montly Salary  52000
13     106  Kiran      Sales  Montly Salary  48000
14     107  Pooja         IT  Montly Salary  65000
15     108  Vijay         HR  Montly Salary  47000
16     101  Rahul         IT     Experience      2
17     102  Priya         HR     Experience      4
18     103   Amit         IT     Experience      6
19     104  Sneha      Sales     Experience      1
20     105  Arjun         HR     Experience      5
21     106  Kiran      Sales     Experience      7
22     107  Pooja         IT     Experience      3
23     108  Vijay         HR     Experience      2

In [18]:
#pivot
pivot_data = df.pivot_table(
    values="Montly Salary",
    index="Department",
    columns="City",
    aggfunc="mean"
)

pivot_data

City        CHENNAI  HYDERABAD   MUMBAI     NEW DELHI
Department
HR          47000.0    52000.0  45000.0           NaN
IT              NaN        NaN      NaN  58333.333333
Sales       40000.0        NaN  48000.0           NaN

In [20]:
#merging
department_info = pd.DataFrame({
    "Department": ["IT", "HR", "Sales"],
    "Manager": ["Anil", "Kavya", "Rohit"],
    "Location": ["Bangalore", "Hyderabad", "Chennai"]
})

df = pd.merge(df, department_info, on="Department", how="left")

df

,Emp_ID,Name,Department,Age,Montly Salary,City,Experience,Bonus,Total Salary,Manager,Location
0,101,Rahul,IT,25,50000,NEW DELHI,2,5000.0,55000.0,Anil,Bangalore
1,102,Priya,HR,28,45000,MUMBAI,4,4500.0,49500.0,Kavya,Hyderabad
2,103,Amit,IT,30,60000,NEW DELHI,6,6000.0,66000.0,Anil,Bangalore
3,104,Sneha,Sales,24,40000,CHENNAI,1,4000.0,44000.0,Rohit,Chennai
4,105,Arjun,HR,29,52000,HYDERABAD,5,5200.0,57200.0,Kavya,Hyderabad
5,106,Kiran,Sales,31,48000,MUMBAI,7,4800.0,52800.0,Rohit,Chennai
6,107,Pooja,IT,27,65000,NEW DELHI,3,6500.0,71500.0,Anil,Bangalore
7,108,Vijay,HR,26,47000,CHENNAI,2,4700.0,51700.0,Kavya,Hyderabad

In [22]:
# saving data to csv file

df.to_csv("Employee.csv")

In [23]:
df

,Emp_ID,Name,Department,Age,Montly Salary,City,Experience,Bonus,Total Salary,Manager,Location
0,101,Rahul,IT,25,50000,NEW DELHI,2,5000.0,55000.0,Anil,Bangalore
1,102,Priya,HR,28,45000,MUMBAI,4,4500.0,49500.0,Kavya,Hyderabad
2,103,Amit,IT,30,60000,NEW DELHI,6,6000.0,66000.0,Anil,Bangalore
3,104,Sneha,Sales,24,40000,CHENNAI,1,4000.0,44000.0,Rohit,Chennai
4,105,Arjun,HR,29,52000,HYDERABAD,5,5200.0,57200.0,Kavya,Hyderabad
5,106,Kiran,Sales,31,48000,MUMBAI,7,4800.0,52800.0,Rohit,Chennai
6,107,Pooja,IT,27,65000,NEW DELHI,3,6500.0,71500.0,Anil,Bangalore
7,108,Vijay,HR,26,47000,CHENNAI,2,4700.0,51700.0,Kavya,Hyderabad